# Generated by Django 2.1 on 2018-12-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('Vary bad', 'Vary bad'), ('Bad', 'Bad'), ('Normal', 'Normal'), ('Good', 'Good'), ('Fine', 'Fine')], max_length=20, verbose_name='Mark')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article', to='blog.Article', verbose_name='Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('login', models.CharField(max_length=20, verbose_name='login')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('about_yourself', models.TextField(max_length=1000, null=True, verbose_name='About yourself')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='blog.User', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_author', to='blog.User', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.User', verbose_name='Article'),
        ),
    ]
