# Generated by Django 2.1 on 2018-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181215_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='favorite_articles', through='blog.Favorites', to='blog.Article', verbose_name='Favorites'),
        ),
    ]
