# Generated by Django 2.1 on 2018-12-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181215_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Comment'),
        ),
    ]
