# Generated by Django 2.1 on 2018-12-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181216_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_comment', to='blog.Comment', verbose_name='Comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ManyToManyField(related_name='commented_article', to='blog.Article', verbose_name='Article'),
        ),
    ]
