# Generated by Django 2.1 on 2019-01-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parrent_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='parrent_comment', to='blog.Comment', verbose_name='Answer'),
            preserve_default=False,
        ),
    ]
