# Generated by Django 2.1 on 2019-01-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_parrent_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parrent_pk',
        ),
        migrations.AddField(
            model_name='comment',
            name='parrent_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='blog.Comment', verbose_name='Answer'),
            preserve_default=False,
        ),
    ]
