# Generated by Django 2.1 on 2019-01-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190115_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parrent_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='blog.Comment', verbose_name='Answer'),
        ),
    ]
