# Generated by Django 2.1 on 2019-01-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190115_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_author', to='blog.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='blog.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parrent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='blog.Comment', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_article', to='blog.Article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_author', to='blog.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_article', to='blog.Article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_author', to='blog.User', verbose_name='Author'),
        ),
    ]
